files:
  - source: /auth/src/*
    translation: /auth/dist/%file_name%.%two_letters_code%.%file_extension%
  - source: /room/src/*.json
    translation: /room/dist/%file_name%.%two_letters_code%.%file_extension%
